# variables used in the build
variables:
  checkout: master
  iteration: '1'

# package builds will always be manually triggered
trigger: none

jobs:
- job: 'msvc2015'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      win64:
        target: msvc2015-win64
  timeoutInMinutes: 0
  steps:
  - script: |
      choco install -yr --no-progress vcbuildtools -ia "/Full"
      pip install -q conan
      cmd /c attrib "C:\Program Files (x86)\Windows Kits\10\include\wdf" +H
    displayName: 'install dependencies'
  - script: |
      git clone --recurse-submodules https://github.com/partychen/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build vagrant $(target) --version - - --iteration $(iteration) wkhtmltopdf
    displayName: 'build package'
  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), ne(variables['Build.Reason'],'PullRequest'))
    displayName: Upload Build Artifacts
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/targets/wkhtmltox/bin/wkhtmltopdf.exe'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  - task: CopyFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'],'PullRequest'))
    displayName: 'Copy files from $(System.DefaultWorkingDirectory)/targets/wkhtmltox/bin/wkhtmltopdf.exe to $(Build.ArtifactStagingDirectory)/publish'
    inputs:
      Contents: |
        targets/wkhtmltox/bin/wkhtmltopdf.exe'
        install.ps1'
        wkhtmltopdf.msvc.exe.nuspec'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
  - task: NuGetToolInstaller@1
    condition: and(succeeded(), ne(variables['Build.Reason'],'PullRequest'))
    displayName: 'Use NuGet '
  - task: NuGetCommand@2
    condition: and(succeeded(), ne(variables['Build.Reason'],'PullRequest'))
    inputs:
      command: pack
      packagesToPack: '$(System.ArtifactStagingDirectory)/publish/wkhtmltopdf.msvc.exe.nuspec'
      versioningScheme: byEnvVar
      versionEnvVar: releaseVersion
  - task: NuGetCommand@2
    condition: and(succeeded(), ne(variables['Build.Reason'],'PullRequest'))
    displayName: 'NuGet push'
    inputs:
      command: push
      publishVstsFeed: '32d1fdf2-56bc-43a3-b791-1f00f9d3ead8'
      allowPackageConflicts: true